### ISSUE TITLE
Wrong device class for Current.

### ISSUE THREAD

**Issue by alexfiftyfour** [kellerza/hassio-sma-em#32] opened 2023-11-01 12:27 UTC
English version:
HA reports an error on the wrong device class for currents.

Following the device class list here: https://www.home-assistant.io/integrations/sensor/
the device class "current" with unit "A" or "mA" should be used for currents.
The below error messages says the device class "energy" is used with the unit "A". 
Can you fix the device class for currents and change it from "energy" to "current"?

German version:
HA meldet einen Fehler wegen einer falschen Device Class für Ströme.

Entsprechend der device class liste hier:  https://www.home-assistant.io/integrations/sensor/
sollte die device class "current" mit der Einheit "A" oder "mA" für Ströme verwendet werden.
In der unten stehenden Fehlermeldung steht, dass die device class "energy" mit der Einheit "A" verwendet wird. 
Könnten Sie die device class für Ströme von "energy" auf "current" umstellen?

Here the error message from the home assistant log:

Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:663
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 13:12:42 (3 occurrences)
Last logged: 13:12:42

    Entity sensor.sma_energy_meter_i1 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'A' which is not a valid unit for the device class ('energy') it is using; expected one of ['MJ', 'GJ', 'Wh', 'kWh', 'MWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
    Entity sensor.sma_energy_meter_i2 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'A' which is not a valid unit for the device class ('energy') it is using; expected one of ['MJ', 'GJ', 'Wh', 'kWh', 'MWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
    Entity sensor.sma_energy_meter_i3 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'A' which is not a valid unit for the device class ('energy') it is using; expected one of ['MJ', 'GJ', 'Wh', 'kWh', 'MWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22

**Comment by kellerza** [comment] 2023-11-08 10:09
Did you try the dev addon?

**Comment by kellerza** [comment] 2023-11-08 10:10
Duplicate of #54

**Closed by kellerza** 2023-11-08 10:10 UTC
